### ISSUE TITLE
Delivery Details missing in Remote Storage 9.18

### ISSUE THREAD

**Issue by nicmitchell** [kaltura/platform-install-packages#174]
I am attempting to set up remote storage in 9.18. I have followed the guidelines here:
https://github.com/blackyboy/RedHat-Centos-Common-Stuffs/blob/master/setup-amazon-S3-remote-storage.md

I am able to put videos in the s3 bucket when I upload content, but I receive the "Media not found" error when trying to preview a video in the KMC. I have added the Policy for s3 (and yes I specified the correct bucket name), and I even manually set all folders and media in s3 to public. I have quadruple checked all those settings.

I set up the initial CloudFront settings, but there is no where to enter the HTTP Delivery Base URL in the Remote Storage settings. So I inserted the value in the database directly under the column 'delivery_http_base_url', but there is no column for https. Regardless, I still receive the "Media not found error".

I have attached a screenshot of the available options in the Remote Storage settings.

![remote-storage](https://cloud.githubusercontent.com/assets/4238222/3486043/11922fb2-0418-11e4-8732-9b16044d5a0f.jpg)

**Comment by renich** [comment]
I could fix mine like this but, mine is grayed out
![screenshot from 2015-01-16 01 21 14](https://cloud.githubusercontent.com/assets/225115/5772840/b8306c72-9d1e-11e4-9d46-94978e44695f.png)

**Comment by renich** [comment]
nicmitchell's comment would have solved my issues; but my input is grayed out... :(

![screenshot from 2015-01-16 01 21 14](https://cloud.githubusercontent.com/assets/225115/5772858/f0e30f8e-9d1e-11e4-8aff-1ba7b69a9e6a.png)

**Comment by jessp01** [comment]
Hello,

I'm sorry but I can't understand which text field is disabled.. please clarify.
Thanks,

**Comment by renich** [comment]
Hello @jessp01 

The input where I should be able to insert nicmitchell's solution is grayed out; disabled; I can't use it.

I am on 10.2.0 but will try 10.3.0 to see if it works better. 

I appreciate any suggestions.

**Comment by jessp01** [comment]
Hello,

I doubt the problem will be resolved with an upgrade.
Did you create a delivery profile? Is the disabled field 'Delivery Profile IDs'?
Also, can you please try to use the script here?
/opt/kaltura/bin/create_remote_storage.php

**Comment by renich** [comment]
Ok; still, I am in the middle of it. Am very interested in the use of nginx. </OOT>

Answering your questions:

- yes, I did. In fact, I am trying to use cloudfront but the delivery profiles, even when enabled, are not showing up on the Remote storage section; when I try to add HTTP and RTMP protocols.

- Yes, it is. I thought it was clear on the screenshot. Forgive me. I will highlight it next time.

- Definitely; once I've upgraded.

Thank you for your genuine interest in helping, @jessp01 and, as You say, "may the source be with us all".

**Comment by renich** [comment]
Ok, on 10.2.0 still.

It seems that I had to use names (system names) without spaces for the delivery profiles. Otherwise, for some reason, they would not be listed.

**Comment by iddrew** [comment]
@renich 

It is greyed out because that field does not accept manual (typing with a keyboard) entry.

To populate that field do the following:
1) Select what delivery type you want to add from the dropdown list (as you can see by default it's on "HTTP")
2) click "Add" and a window pops up with all possible delivery profiles with that type.  
3) click on the delivery profile and click the "Select >" button
4) Click "OK"
5) Click "Save"

**Comment by renich** [comment]
@iddrew I fixed that renaming the delivery profiles to non-spaced names. This had them working. So, the issue is no more.

**Comment by nukepuppy** [comment]
so what is the proper process for adding this? it still doesn't seem clear i want to set the " HTTP Delivery Base URL" as mentioned in the document.   How can this not be clearer?

I know about create_remote_storage.php  - but let's pretend there is a world where not everyone has SSH access for good reasons
